<?php

/**
 * Builds resources/rules/peppol-rules.php from the compiled official Schematron in
 * docs/assets/validator (the SEF files the online validator runs).
 *
 * Run it after updating those files to a new OpenPEPPOL release:
 *
 *     php examples/validate/build_rule_catalog.php
 *
 * Every svrl:failed-assert in a SEF file holds the rule id, the flag, the XPath test and the
 * rule text as literal strings; the context is the element the enclosing template matches.
 * A rule that appears more than once (for an Invoice and for a CreditNote) is kept once.
 */
$root = dirname(__DIR__, 2);
$validatorDir = $root.'/docs/assets/validator';
$release = json_decode((string) file_get_contents($validatorDir.'/release.json'), true)['release'] ?? null;

if (! is_string($release)) {
    fwrite(STDERR, "No release in {$validatorDir}/release.json\n");
    exit(1);
}

/**
 * The literal strings below a SEF node, in document order.
 *
 * @return list<string>
 */
function literalStrings(mixed $node): array
{
    if (! is_array($node)) {
        return [];
    }

    $strings = (($node['N'] ?? null) === 'str' && isset($node['val'])) ? [(string) $node['val']] : [];

    foreach ($node as $key => $child) {
        if ($key !== 'val' && is_array($child)) {
            array_push($strings, ...literalStrings($child));
        }
    }

    return $strings;
}

/**
 * The local name of the element a failed-assert reports on, from the type of its location.
 */
function contextOf(mixed $node): ?string
{
    if (! is_array($node)) {
        return null;
    }

    if (($node['N'] ?? null) === 'dot' && isset($node['sType']) && preg_match('/\}([A-Za-z]+)$/', (string) $node['sType'], $matches)) {
        return $matches[1];
    }

    foreach ($node as $child) {
        $context = contextOf($child);
        if ($context !== null) {
            return $context;
        }
    }

    return null;
}

/**
 * Collect every failed-assert below a SEF node.
 *
 * @param  array<string, array{flag: string, text: string, test: string, context: string|null, source: string}>  $rules
 */
function collectRules(mixed $node, string $source, array &$rules): void
{
    if (! is_array($node)) {
        return;
    }

    if (($node['N'] ?? null) === 'elem' && ($node['name'] ?? null) === 'svrl:failed-assert') {
        $attributes = [];
        $text = '';
        $location = null;

        foreach ($node['C'][0]['C'] ?? [] as $child) {
            if (($child['N'] ?? null) === 'att') {
                $attributes[$child['name']] = literalStrings($child)[0] ?? '';
                if ($child['name'] === 'location') {
                    $location = contextOf($child);
                }
            } elseif (($child['name'] ?? null) === 'svrl:text') {
                $text = trim(implode('', literalStrings($child)));
            }
        }

        $id = $attributes['id'] ?? '';
        if ($id !== '' && ! isset($rules[$id])) {
            $rules[$id] = [
                'flag' => $attributes['flag'] ?? 'fatal',
                // The text repeats the id: "[BR-55]-Each Preceding Invoice reference ..."
                'text' => (string) preg_replace('/^\['.preg_quote($id, '/').'\]-?\s*/', '', $text),
                'test' => $attributes['test'] ?? '',
                'context' => $location,
                'source' => $source,
            ];
        }

        return;
    }

    foreach ($node as $child) {
        collectRules($child, $source, $rules);
    }
}

$rules = [];
foreach (['CEN-EN16931-UBL' => 'CEN', 'PEPPOL-EN16931-UBL' => 'PEPPOL'] as $file => $source) {
    $sef = json_decode((string) file_get_contents("{$validatorDir}/{$file}.sef.json"), true);
    collectRules($sef, $source, $rules);
}

ksort($rules, SORT_NATURAL);

$target = $root.'/resources/rules/peppol-rules.php';
if (! is_dir(dirname($target))) {
    mkdir(dirname($target), 0755, true);
}

file_put_contents($target, "<?php\n\n"
    ."// Generated by examples/validate/build_rule_catalog.php from the official OpenPEPPOL Schematron,\n"
    ."// release {$release}. Do not edit by hand: change the generator or update the SEF files.\n\n"
    .'return '.var_export(['release' => $release, 'rules' => $rules], true).";\n");

echo count($rules)." rules from release {$release} written to resources/rules/peppol-rules.php\n";
